mysql:
    use: true
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: 123
    tabela: cash_
msgs:
    secondline: ''
    

Prefixo_automsg: '&6&l* &f'
Mensagens:
   - ''